version: '3'

services:
  php:
    build:
      args:
        USERNAME: defaultuser
        USER_UID: 1000
        USER_GID: 1000
      context: .
      dockerfile: ./docker2/php/Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    user: defaultuser
    volumes:
      - .:/var/www
    working_dir: /var/www

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./.datastorage:/var/lib/mysql

  nginx:
    depends_on:
      - php
      - mysql
    image: nginx:1.19
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker2/nginx/default.conf:/etc/nginx/conf.d/default.conf

  node:
    image: node:15.3
    user: node
    volumes:
      - .:/home/node
    working_dir: /home/node

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    ports:
     - 8080:80
